name: BedWars-LobbyShop
version: '${project.version}'
main: com.suolis.bedwarslobbyshop.LobbyShop
softdepend:
  - BedWars1058
  - BedWars2023
commands:
  shop:
    description: Used to open the shop inventory in the lobby!